import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ssr,
}: Readonly<{
  children: React.ReactNode;
  ssr: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="flex min-h-screen flex-col items-center gap-4 p-24">
            {children}
            {/* SSR */}
            <Suspense fallback={<div>Setting initial pokemon...</div>}>
              {ssr}
            </Suspense>
          </main>
        </Providers>
      </body>
    </html>
  );
}
